### ISSUE TITLE
Google Client 有问题

### ISSUE THREAD

**Issue by libern** [shen2/zenapi#1]
在使用Google Client访问api的时候，那个参数key应该是access_token

**Comment by libern** [comment]
而且，Undefined property: ZenAPI\GoogleClient::$format，client 返回的东西也有问题

**Comment by shen2** [comment]
我跑了一下测试程序，用key=access_token是对的，有可能不同的api接口是不同的。
请帖一下你的测试程序。

format和decode_json的相关代码，稍后会去掉。

**Comment by shen2** [comment]
我查了一下google官方的api client，也是key

**Comment by libern** [comment]
```
  $client = $this->getClient($access_token);
  $response = $client->get('userinfo/v2/me');
```

如果要获取用户的资料，你是怎样做到的？我用上面的这个，是不可以的。

**Comment by shen2** [comment]
$this->getClient()是什么方法？我们代码里好像没有这个函数

**Comment by libern** [comment]
```
  $client = new \ZenAPI\GoogleClient($access_token);
  $response = $client->get('userinfo/v2/me');
```

这个代码

**Comment by shen2** [comment]
我确认是个问题，已经修正，你测试一下，谢谢！
